/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hackupc2018;

import java.awt.BorderLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class VistaSolucio extends javax.swing.JFrame {

    /**
     * Creates new form VistaSolucio
     */
    private ControladorPresentacio CtrlPresentacio;
    private String[] nomsColumnes;
    private Object[][] data;
    private JTable taula;
    

    public VistaSolucio(ControladorPresentacio CP) {
        this.CtrlPresentacio = CP;
        HashMap solucio = this.CtrlPresentacio.getSolucio();
        this.CtrlPresentacio.incrementarIterador();
        this.nomsColumnes = new String[solucio.size()];
        int i = 0;
        for (Iterator it = solucio.keySet().iterator(); it.hasNext();) {
            String colla = (String)it.next();
            this.nomsColumnes[i] = colla;
            ++i;
        }
        i = 0;
        this.data = new Object[solucio.size()][this.CtrlPresentacio.getMonitors().size()];
        for (Iterator it = solucio.values().iterator(); it.hasNext();) {
            ArrayList monitors = (ArrayList) it.next();
            for (int j = 0; j < monitors.size(); ++j) {
                this.data[i][j] = monitors.get(j);
            }
            ++i;
        }
        this.taula = new JTable(data, nomsColumnes);
        JPanel Panel = new JPanel((LayoutManager) taula);
        taula.setFillsViewportHeight(true);
      //  Panel.setLayout(new BorderLayout());
        Panel.add(taula, BorderLayout.CENTER);
       // initComponents();
    }

    public void ferVisible() {
        jLabel1.setEnabled(true);
        jPanel1.setEnabled(true);
    }

    public void desactivar() {
        jLabel1.setEnabled(false);
        jPanel1.setEnabled(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Georgia Pro Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("SOLUCIÓ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
